name: test

on:
#  push: #
  workflow_dispatch: # (manually)

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: johannesflake/oscar
      
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: /home/oscar/
      - name: do test
        run: |
          echo Hello, world!
          julia -v
          cd /home/oscar
          pwd
          ls
          julia tests.jl
      
