name: test

on:
#  push: #
  workflow_dispatch: # (manually)

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: johannesflake/oscar
      options: -v $(pwd):/home/oscar/local -w /home/oscar/local
      
    steps:
      - name: do test
        run: |
          echo Hello, world!
          julia -v
          pwd
          ls
          ls /github/home/
          ls /__w/
          cd /home/oscar/local
          ls
      
