name: test

on:
  schedule:
    - cron: '0 2 2 * *' # once a month
  push:
    paths:
      - '**.ipynb'
  workflow_dispatch: # (manually)

jobs:
  test:
    runs-on: ubuntu-latest
      
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: test
        uses: addnab/docker-run-action@v3
        with:
          image: johannesflake/oscar
          options: -v ${{ github.workspace }}:/home/oscar/work -w /home/oscar/work
          run: julia tests.jl

