name: test

on:
#  push: #
  workflow_dispatch: # (manually)

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: johannesflake/oscar
      options: --user root
      
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: do test
        run: |
          echo Hello, world!
          julia -v
          pwd
          ls
          su -c "julia tests.jl" -m oscar
      
